/**
 * ============================================================================
 * LEGAL DOCUMENTS
 * ============================================================================
 *
 * ⚠️  REVIEW BEFORE RELYING ON THESE.
 *
 * This content was written to describe what this codebase ACTUALLY does —
 * every collection, processor and retention statement below was derived from
 * the form schemas in `src/lib/validation/schemas.ts`, the adapters in
 * `src/lib/integrations/`, and the cookie and storage use in `portal/auth.ts`,
 * `admin/auth.ts` and `SplashScreen.tsx`. It is accurate to the build.
 *
 * It is NOT legal advice, and it has not been reviewed by a lawyer. Two things
 * follow from that:
 *
 *   1. Have it reviewed. PIPEDA compliance depends on facts about your
 *      business that source code cannot see — who inside OAX Tech accesses
 *      enquiries, what you do with them afterwards, and what you have agreed
 *      with clients elsewhere.
 *
 *   2. KEEP IT TRUE. These statements stop being accurate the moment the code
 *      changes. Adding analytics, a payment processor, a CRM sync or a chat
 *      widget each makes a specific sentence below false. Update this file in
 *      the same commit as the change, not afterwards.
 */

export interface LegalBlock {
  heading: string;
  paragraphs?: string[];
  /** Rendered as a bulleted list beneath the paragraphs. */
  list?: string[];
}

export interface LegalDocument {
  title: string;
  /** ISO date this version took effect. Shown to the reader. */
  effective: string;
  /** One-paragraph plain-language summary, set above the document proper. */
  summary: string;
  blocks: LegalBlock[];
}

/* -------------------------------------------------------------------------- */
/* Privacy                                                                     */
/* -------------------------------------------------------------------------- */

export const privacyPolicy: LegalDocument = {
  title: "Privacy Policy",
  effective: "2026-08-28",
  summary:
    "We collect only what you type into a form on this site, we use it to reply to you, and we do not sell it or share it for advertising. This page explains exactly what is collected, who processes it on our behalf, how long we keep it, and how to ask us to delete it.",
  blocks: [
    {
      heading: "Who this policy covers",
      paragraphs: [
        "OAX Tech is a technology and digital-growth agency based in Calgary, Alberta, Canada. This policy applies to this website and to the enquiries we receive through it.",
        "We handle personal information in accordance with Canada's Personal Information Protection and Electronic Documents Act (PIPEDA) and Alberta's Personal Information Protection Act (PIPA).",
      ],
    },
    {
      heading: "What we collect, and when",
      paragraphs: [
        "We do not ask for personal information to browse this site. We collect it only when you choose to submit one of our forms, and only the fields that form actually contains:",
      ],
      list: [
        "Contact form — your name, email address, an optional phone number, the subject you select, and your message.",
        "Quote request — your name, email address, phone number, an optional company name and current website, the service and package you select, your project description, approximate page count, requested features, budget range and optional target completion date.",
        "Consultation booking — your name, email address, phone number, company name, an optional current website, the service you want to discuss, your budget range, a description of what you are looking to build, and the date, time and time zone you select.",
        "Newsletter — your email address, and nothing else.",
      ],
    },
    {
      heading: "Information collected automatically",
      paragraphs: [
        "Our hosting provider records standard server logs for every request, including IP address, browser user-agent, the page requested and the time. These are generated by the infrastructure rather than by us, and we use them only to keep the site running and secure.",
        "We also record your IP address briefly when you submit a form. This is used to rate-limit submissions so that automated systems cannot flood our enquiry inbox. These records contain an IP address and a timestamp and nothing else, and are cleared automatically within minutes.",
        "We do not currently load any third-party analytics, advertising or session-recording script on this site. If that changes, we will update this policy before it does, not after.",
      ],
    },
    {
      heading: "Why we collect it",
      paragraphs: [
        "To reply to your enquiry, prepare a quote or proposal, schedule and hold a consultation, send you the newsletter if you asked for it, and keep records of the work we have been asked to do.",
        "By submitting a form you consent to us using your information for those purposes. We do not use it for anything else, and we do not create profiles, score leads automatically, or make automated decisions about you.",
      ],
    },
    {
      heading: "Who else processes it",
      paragraphs: [
        "We use a small number of service providers to operate this site. They process information on our instructions only, and are not permitted to use it for their own purposes:",
      ],
      list: [
        "Our hosting provider, which serves the website and generates the server logs described above.",
        "Our database provider, which stores submitted enquiries.",
        "Our email delivery provider, which sends us a notification when you submit a form. Your message and reply-to address pass through it.",
        "Our scheduling provider, which holds consultation bookings and sends the calendar invitation. It receives your name, email address and chosen time.",
      ],
    },
    {
      heading: "What we never do",
      paragraphs: [
        "We do not sell your personal information. We do not rent, trade or share it with advertisers or data brokers. We do not use it to target advertising to you anywhere, on this site or off it.",
        "We disclose personal information outside the providers listed above only where the law requires it of us.",
      ],
    },
    {
      heading: "Where it is stored",
      paragraphs: [
        "Our providers may store and process information outside Canada, including in the United States. Where that is the case, the information is subject to the laws of that country and may be accessible to its courts and law-enforcement authorities. If you would prefer not to have your information processed outside Canada, contact us and we will arrange another way to work together.",
      ],
    },
    {
      heading: "How long we keep it",
      paragraphs: [
        "Enquiries, quote requests and booking records are kept for as long as we may reasonably need them for the relationship they relate to, and for a period afterwards for our business records. Newsletter subscriptions are kept until you unsubscribe. Rate-limiting records are cleared within minutes.",
        "If you ask us to delete your information, we will, except where we are required to keep a record for legal or accounting reasons.",
      ],
    },
    {
      heading: "Cookies and browser storage",
      paragraphs: [
        "This site sets no advertising or tracking cookies, and there is no cookie consent banner because there is nothing to consent to.",
        "If you sign in to the client portal or the internal admin, we set one session cookie so you stay signed in. It is marked HttpOnly, so it cannot be read by scripts in your browser, and it expires after four hours or when you sign out.",
        "We also store a single flag in your browser's session storage to remember that you have already seen the opening animation, so it does not replay on every page. It contains no personal information, never leaves your browser, and is discarded when you close the tab.",
      ],
    },
    {
      heading: "How we protect it",
      paragraphs: [
        "Traffic to this site is encrypted in transit. Account passwords, where accounts exist, are stored only as Argon2id hashes and never in readable form. Sign-in is rate-limited against brute-force attempts. Access to submitted enquiries is limited to the people at OAX Tech who need it to do the work.",
        "No system is perfectly secure, and we will not claim otherwise. If a breach affects your information and creates a real risk of significant harm, we will notify you and the Office of the Privacy Commissioner of Canada as PIPEDA requires.",
      ],
    },
    {
      heading: "Your rights",
      paragraphs: [
        "You can ask us for a copy of the personal information we hold about you, ask us to correct it if it is wrong, ask us to delete it, or withdraw your consent to us using it. You can unsubscribe from the newsletter at any time using the link in any issue.",
        "We will respond to a request within 30 days. There is no charge. We may need to confirm your identity first, so that we do not disclose your information to someone else asking on your behalf.",
      ],
    },
    {
      heading: "Children",
      paragraphs: [
        "This site is intended for businesses and the people who run them. It is not directed at children, and we do not knowingly collect personal information from anyone under 13. If you believe a child has sent us information, contact us and we will delete it.",
      ],
    },
    {
      heading: "Changes to this policy",
      paragraphs: [
        "If we change how we handle personal information, we will update this page and change the effective date at the top. Material changes will be described rather than made quietly.",
      ],
    },
    {
      heading: "Complaints",
      paragraphs: [
        "If you are not satisfied with how we have handled your information, please tell us first — we would rather fix it directly. You also have the right to complain to the Office of the Privacy Commissioner of Canada at priv.gc.ca, or to the Office of the Information and Privacy Commissioner of Alberta at oipc.ab.ca.",
      ],
    },
  ],
};

/* -------------------------------------------------------------------------- */
/* Terms                                                                       */
/* -------------------------------------------------------------------------- */

export const termsOfService: LegalDocument = {
  title: "Terms of Service",
  effective: "2026-08-28",
  summary:
    "These terms cover your use of this website. They do not govern project work — that is set out in the written proposal and agreement we sign with each client, and where the two differ, the signed agreement wins.",
  blocks: [
    {
      heading: "About these terms",
      paragraphs: [
        "By using this website you agree to these terms. If you do not agree with them, please do not use the site.",
        "These terms cover the website itself. They are not the contract for any project. Scope, price, timeline, ownership and payment for actual work are set out in the written proposal and agreement signed by both parties, and that agreement takes precedence over anything on this site.",
      ],
    },
    {
      heading: "Who we are",
      paragraphs: [
        "OAX Tech is a technology and digital-growth agency based in Calgary, Alberta, Canada, providing website design and development, custom software, AI and workflow automation, marketing consulting, and SEO.",
      ],
    },
    {
      heading: "Using this site",
      paragraphs: ["You may read, browse and share this site freely. You may not:"],
      list: [
        "use it for any unlawful purpose, or to send unlawful, misleading or abusive content through our forms;",
        "attempt to gain unauthorised access to any part of the site, its infrastructure, the client portal or any account that is not yours;",
        "probe, scan or test the security of the site, or interfere with its normal operation;",
        "scrape or harvest content or contact details in bulk, or use automated systems to submit our forms.",
      ],
    },
    {
      heading: "Pricing, quotes and proposals",
      paragraphs: [
        "Prices, packages and timelines shown on this site are indicative and provided to help you plan. They are not an offer and are not binding.",
        "A quote becomes firm only when we issue it in writing, for your specific project, after we understand the scope. Requesting a quote does not create a contract, and neither does our replying to it.",
        "We may change our published pricing at any time. A change does not affect a written quote already issued to you within its stated validity period.",
      ],
    },
    {
      heading: "Consultations",
      paragraphs: [
        "The initial 30-minute consultation is free and carries no obligation on either side. It is a conversation about your project, not the delivery of professional advice you should act on without further work.",
        "Where a consultation is booked through this site, the time is reserved through our scheduling provider. Please let us know if you need to reschedule or cancel.",
      ],
    },
    {
      heading: "Client portal",
      paragraphs: [
        "The client portal is provided to clients with an active engagement, for viewing project progress, files, approvals and invoices.",
        "You are responsible for keeping your sign-in details confidential and for activity under your account. Tell us immediately if you believe your account has been accessed by someone else. We may suspend access where we believe an account has been compromised or these terms have been breached.",
      ],
    },
    {
      heading: "Intellectual property",
      paragraphs: [
        "The content, design, code, branding and layout of this website belong to OAX Tech or to the parties who licensed them to us, and are protected by copyright and trade-mark law. You may not copy, reproduce or reuse them without our written permission.",
        "Ownership of the work we produce for a client — the code, designs and content of a project — is dealt with in that project's signed agreement, not here. Client names, logos and trade marks shown on this site remain the property of their respective owners and are used with permission.",
      ],
    },
    {
      heading: "Links to other sites",
      paragraphs: [
        "This site links to websites we do not control, including projects we have worked on. We provide those links for reference. We are not responsible for the content, accuracy or practices of any site we do not operate, and a link is not an endorsement.",
      ],
    },
    {
      heading: "No guarantee of results",
      paragraphs: [
        "Marketing and SEO outcomes depend on factors outside anyone's control, including search-engine algorithms, competitors and your own market. We do not guarantee particular rankings, traffic levels, conversion rates or revenue, and you should treat any such guarantee from anyone with suspicion.",
        "Where we publish a client result, it is a measured figure from a specific engagement over a stated period. It describes what happened for that client and is not a prediction of what will happen for you.",
      ],
    },
    {
      heading: "The site is provided as it is",
      paragraphs: [
        "We work to keep this site accurate, available and secure, but we provide it on an “as is” and “as available” basis. We do not warrant that it will be uninterrupted, error-free, or free of harmful components, and content may become out of date.",
        "Nothing on this site is professional, legal, financial or technical advice for your specific situation. Talk to us, or to an appropriate professional, before acting on it.",
      ],
    },
    {
      heading: "Limitation of liability",
      paragraphs: [
        "To the fullest extent permitted by law, OAX Tech is not liable for indirect, incidental, special or consequential loss, or for lost profits, revenue, data or business opportunity, arising from your use of this website.",
        "Nothing in these terms limits liability that cannot be limited by law, including liability for fraud, or for death or personal injury caused by negligence. Our liability in connection with project work is governed by the signed agreement for that project.",
      ],
    },
    {
      heading: "Governing law",
      paragraphs: [
        "These terms are governed by the laws of the Province of Alberta and the applicable laws of Canada. The courts of Alberta have jurisdiction over any dispute arising from them.",
      ],
    },
    {
      heading: "Changes to these terms",
      paragraphs: [
        "We may update these terms from time to time. The effective date at the top shows when the current version took effect, and continuing to use the site after a change means you accept the updated terms.",
      ],
    },
  ],
};
